config/routes.rb
Rails.application.routes.draw do
  get 'agent_home/index'

  get 'user_home/index'

  devise_for :users
  devise_for :agents

  resources :homes

  resources :rentals

  resources :commercials

  resources :lands

  resources :areas

   root 'homes#index'

end

app/models/land.rb
class Land < ActiveRecord::Base
  belongs_to :area
  belongs_to :agent

    has_attached_file :image, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
  before_action :set_land, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_agent!, except: [:index, :show]



  # GET /lands
  # GET /lands.json
  def index
    @lands = Land.all
  end

  # GET /lands/1
  # GET /lands/1.json
  def show
  end

  # GET /lands/new
  def new
    @land = current_agent.lands.build
  end

  # GET /lands/1/edit
  def edit
  end

  # POST /lands
  # POST /lands.json
  def create
    @land = current_agent.lands.build(land_params)

    respond_to do |format|
      if @land.save
        format.html { redirect_to @land, notice: 'Land was successfully created.' }
        format.json { render :show, status: :created, location: @land }
      else
        format.html { render :new }
        format.json { render json: @land.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lands/1
  # PATCH/PUT /lands/1.json
  def update
    respond_to do |format|
      if @land.update(land_params)
        format.html { redirect_to @land, notice: 'Land was successfully updated.' }
        format.json { render :show, status: :ok, location: @land }
      else
        format.html { render :edit }
        format.json { render json: @land.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lands/1
  # DELETE /lands/1.json
  def destroy
    @land.destroy
    respond_to do |format|
      format.html { redirect_to lands_url, notice: 'Land was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_land
      @land = Land.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def land_params
      params.require(:land).permit(:price, :size, :amenities, :description, :area_id, :image)
    end
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/views/lands/_form.html.erb
<%= form_for @land, :html => { :multipart => true } do |f| %>
  <% if @land.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@land.errors.count, "error") %> prohibited this land from being saved:</h2>

      <ul>
      <% @land.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :amenities %><br>
    <%= f.text_field :amenities %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.text_field :area_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lands/edit.html.erb
<h1>Editing land</h1>
<%= image_tag @land.image.url(:medium) %>

<%= render 'form' %>

<%= link_to 'Show', @land %> |
<%= link_to 'Back', lands_path %>

app/views/lands/index.html.erb
<h1>Listing lands</h1>
<%= link_to 'New Land', new_land_path %>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Price</th>
      <th>Size</th>
      <th>Amenities</th>
      <th>Description</th>
      <th>Area</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lands.each do |land| %>
      <tr>
        <td><%= image_tag land.image.url(:thumb) %></td>
        <td><%= land.price %></td>
        <td><%= land.size %></td>
        <td><%= land.amenities %></td>
        <td><%= land.description %></td>
        <td><%= land.area %></td>
        <td><%= land.agent.email%></td>
        <td><%= link_to 'Show', land %></td>
        
        <%# if land.agent == current_agent? %>
          <td><%= link_to 'Edit', edit_land_path(land) %></td>
          <td><%= link_to 'Destroy', land, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lands/new.html.erb
<h1>New land</h1>

<%= render 'form' %>

<%= link_to 'Back', lands_path %>

app/views/lands/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag @land.image.url(:large) %>
</p>
<p>
  <strong>Price:</strong>
  <%= @land.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @land.size %>
</p>

<p>
  <strong>Amenities:</strong>
  <%= @land.amenities %>
</p>

<p>
  <strong>Description:</strong>
  <%= @land.description %>
</p>

<p>
  <strong>Area:</strong>
  <%= @land.area %>
</p>

<%= link_to 'Edit', edit_land_path(@land) %> |
<%= link_to 'Back', lands_path %>