config/routes.rb
Rails.application.routes.draw do
  get 'agent_home/index'

  get 'user_home/index'

  devise_for :users
  devise_for :agents

  resources :homes

  resources :rentals

  resources :commercials

  resources :lands

  resources :areas

   root 'homes#index'

end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :area
  belongs_to :agent

  	has_attached_file :image, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_agent!, except: [:index, :show]


  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = current_agent.rentals.build
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = current_agent.rentals.build(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:price, :bedroom, :amenities, :description, :area_id, :image)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_for @rental, :html => { :multipart => true } do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.number_field :bedroom %>
  </div>
  <div class="field">
    <%= f.label :amenities %><br>
    <%= f.text_field :amenities %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.text_field :area_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing rental</h1>
<%= image_tag @rental.image.url(:medium) %>
<%= render 'form' %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<h1>Listing rentals</h1>
<%= link_to 'New Rental', new_rental_path %>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Price</th>
      <th>Bedroom</th>
      <th>Amenities</th>
      <th>Description</th>
      <th>Area</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= image_tag rental.image.url(:thumb) %></td>
        <td><%= rental.price %></td>
        <td><%= rental.bedroom %></td>
        <td><%= rental.amenities %></td>
        <td><%= rental.description %></td>
        <td><%= rental.area %></td>
        <td><%= rental.agent.email %></td> <%# change to username%>
        <td><%= link_to 'Show', rental %></td>
        
        <%# if rental.agent == current_agent? %>
          <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
          <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/rentals/new.html.erb
<h1>New rental</h1>
<%= image_tag @rental.image.url(:medium) %>
<%= render 'form' %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag @rental.image.url(:large) %>
</p>
<p>
  <strong>Price:</strong>
  <%= @rental.price %>
</p>

<p>
  <strong>Bedroom:</strong>
  <%= @rental.bedroom %>
</p>

<p>
  <strong>Amenities:</strong>
  <%= @rental.amenities %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rental.description, :class => "tinymce", :rows => 40, :cols => 120 %>
</p>

<p>
  <strong>Area:</strong>
  <%= @rental.area %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>