config/routes.rb
Rails.application.routes.draw do
  get 'agent_home/index'

  get 'user_home/index'

  devise_for :users
  devise_for :agents

  resources :homes

  resources :rentals

  resources :commercials

  resources :lands

  resources :areas

   root 'homes#index'

end

app/models/commercial.rb
class Commercial < ActiveRecord::Base
  belongs_to :area
  belongs_to :agent

  	has_attached_file :image, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/commercials_controller.rb
class CommercialsController < ApplicationController
  before_action :set_commercial, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_agent!, except: [:index, :show]



  # GET /commercials
  # GET /commercials.json
  def index
    @commercials = Commercial.all
  end

  # GET /commercials/1
  # GET /commercials/1.json
  def show
  end

  # GET /commercials/new
  def new
    @commercial = current_agent.commercials.build
  end

  # GET /commercials/1/edit
  def edit
  end

  # POST /commercials
  # POST /commercials.json
  def create
    @commercial = current_agent.commercials.build(commercial_params)

    respond_to do |format|
      if @commercial.save
        format.html { redirect_to @commercial, notice: 'Commercial was successfully created.' }
        format.json { render :show, status: :created, location: @commercial }
      else
        format.html { render :new }
        format.json { render json: @commercial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commercials/1
  # PATCH/PUT /commercials/1.json
  def update
    respond_to do |format|
      if @commercial.update(commercial_params)
        format.html { redirect_to @commercial, notice: 'Commercial was successfully updated.' }
        format.json { render :show, status: :ok, location: @commercial }
      else
        format.html { render :edit }
        format.json { render json: @commercial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commercials/1
  # DELETE /commercials/1.json
  def destroy
    @commercial.destroy
    respond_to do |format|
      format.html { redirect_to commercials_url, notice: 'Commercial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commercial
      @commercial = Commercial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commercial_params
      params.require(:commercial).permit(:price, :bedroom, :amenities, :description, :area_id, :image)
    end
end

app/helpers/commercials_helper.rb
module CommercialsHelper
end

app/views/commercials/_form.html.erb
<%= form_for @commercial, :html => { :multipart => true } do |f| %>
  <% if @commercial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commercial.errors.count, "error") %> prohibited this commercial from being saved:</h2>

      <ul>
      <% @commercial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.number_field :bedroom %>
  </div>
  <div class="field">
    <%= f.label :amenities %><br>
    <%= f.text_field :amenities %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"tinymce", :rows => 40, :cols => 120 %>
  </div>
  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.text_field :area_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commercials/edit.html.erb
<h1>Editing commercial</h1>
<%= image_tag @commercial.image.url(:medium) %>


<%= render 'form' %>

<%= link_to 'Show', @commercial %> |
<%= link_to 'Back', commercials_path %>

app/views/commercials/index.html.erb
<%#= tinymce_assets %> <!--no bloody idea why it aint working-->
<!-- <script type="text/javascript" src="/assets/tinymce.js">-->

<h1>Listing commercials</h1>
<%= link_to 'New Commercial', new_commercial_path %>
<table>
  <thead>
    <tr>
      <th></th>
      <th>Price</th>
      <th>Bedroom</th>
      <th>Amenities</th>
      <th>Description</th>
      <th>Area</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commercials.each do |commercial| %>
      <tr>
        <td><%= image_tag commercial.image.url(:thumb) %></td>
        <td><%= commercial.price %></td>
        <td><%= commercial.bedroom %></td>
        <td><%= commercial.amenities %></td>
        <td><%= commercial.description %></td>
        <td><%= commercial.area %></td>
        <td><%= commercial.agent.email%></td>
        <td><%= link_to 'Show', commercial %></td>
        
         <%# if commercial.agent == current_agent? %>
          <td><%= link_to 'Edit', edit_commercial_path(commercial) %></td>
          <td><%= link_to 'Destroy', commercial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/commercials/new.html.erb
<h1>New commercial</h1>

<%= image_tag @commercial.image.url(:medium) %>
<%= render 'form' %>

<%= link_to 'Back', commercials_path %>

app/views/commercials/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= image_tag @commercial.image.url(:large) %>
</p>
<p>
  <strong>Price:</strong>
  <%= @commercial.price %>
</p>

<p>
  <strong>Bedroom:</strong>
  <%= @commercial.bedroom %>
</p>

<p>
  <strong>Amenities:</strong>
  <%= @commercial.amenities %>
</p>

<p>
  <strong>Description:</strong>
  <%= @commercial.description %>
</p>

<p>
  <strong>Area:</strong>
  <%= @commercial.area %>
</p>

<%= link_to 'Edit', edit_commercial_path(@commercial) %> |
<%= link_to 'Back', commercials_path %>