config/routes.rb
Rails.application.routes.draw do
  get 'agent_home/index'

  get 'user_home/index'

  devise_for :users
  devise_for :agents

  resources :homes

  resources :rentals

  resources :commercials

  resources :lands

  resources :areas

   root 'homes#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
	belongs_to :agent
	
	has_many :lands
	has_many :commercials
	has_many :rentals

	#Note to future self: We warned you that having an image for the area was a bad idea as this resource is shared by many people.
	#it was further recomended that we implement a javascript/jquery plugin for maps to shwo a map of the area. Nota Bene, this area shouldnt have and index.
	
	has_attached_file :image, :styles => { :large => "600x600>", :medium => "300x300>", :thumb => "150x150>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_agent!, except: [:index, :show]



  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = current_agent.areas.build
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = current_agent.areas.build(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:county, :location, :image)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for @area, :html => { :multipart => true } do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :county %><br>
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing area</h1>
<%= image_tag @area.image.url(:medium) %>
<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<h1>Listing areas</h1>
<%= link_to 'New Area', new_area_path %>
<table>
  <thead>
    <tr>
      <th></th>
      <th>County</th>
      <th>Location</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= image_tag area.image.url(:thumb) %></td>
        <td><%= area.county %></td>
        <td><%= area.location %></td>
        <td><%= area.agent.email%></td>
        <td><%= link_to 'Show', area %></td>
        
        <%# if area.agent == current_agent? %>
          <td><%= link_to 'Edit', edit_area_path(area) %></td>
          <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%# end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= image_tag @area.image.url(:medium) %>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<%= image_tag @area.image.url(:large) %>
</p>
<p>
  <strong>County:</strong>
  <%= @area.county %>
</p>

<p>
  <strong>Location:</strong>
  <%= @area.location %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>